services:
  - type: web
    name: mealplanner-chatbot
    env: python
    region: singapore
    plan: free
    buildCommand: ""
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: EDAMAM_APP_ID
        sync: false
      - key: EDAMAM_APP_KEY
        sync: false
